# Generated by Django 5.0.6 on 2024-05-28 01:23

import localflavor.br.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14)),
            ],
        ),
    ]
