# Generated by Django 5.0.6 on 2024-05-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='cpf',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='default_value_here', max_length=150),
        ),
    ]
